{% set name = "sshuttle" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sshuttle-{{ version }}.tar.gz
  sha256: f5a3ed1e5ab1213c7a6df860af41f1a903ab2cafbfef71f371acdcff21e69ee6

build:
  number: 0
  noarch: python
  entry_points:
    - sshuttle = sshuttle.cmdline:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6

test:
  imports:
    - sshuttle
    - sshuttle.methods
  commands:
    - pip check
    - sshuttle --help
  requires:
    - pip

about:
  home: https://github.com/sshuttle/sshuttle
  summary: Full-featured" VPN over an SSH tunnel
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
