{% set name = "sshuttle" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sshuttle-{{ version }}.tar.gz
  sha256: f1f82bc59c45745df7543f38b0fa0f1a6a34d8a9e17dd8d9e5e259f069c763d6

build:
  number: 0
  noarch: python
  entry_points:
    - sshuttle = sshuttle.cmdline:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - python >=3.8

test:
  imports:
    - sshuttle
    - sshuttle.methods
  commands:
    - pip check
    - sshuttle --help
  requires:
    - pip

about:
  home: https://github.com/sshuttle/sshuttle
  summary: Full-featured" VPN over an SSH tunnel
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
